#
# DO NOT MODIFY!!!!
# This file is automatically generated by Racc 1.4.12
# from Racc grammer file "".
#

require 'racc/parser.rb'
module TPPlus
  class Parser < Racc::Parser


  include TPPlus::Nodes

  attr_reader :interpreter
  def initialize(scanner, interpreter = TPPlus::Interpreter.new)
    @scanner       = scanner
    @interpreter   = interpreter
    super()
  end

  def next_token
    t = @scanner.next_token
    @interpreter.line_count += 1 if t && t[0] == :NEWLINE

    #puts t.inspect
    t
  end

  def parse
    #@yydebug =true

    do_parse
    @interpreter
  end

  def on_error(t, val, vstack)
    raise ParseError, sprintf("Parse error on line #{@scanner.tok_line} column #{@scanner.tok_col}: %s (%s)",
                                val.inspect, token_to_str(t) || '?')
  end

  class ParseError < StandardError ; end
##### State transition tables begin ###

racc_action_table = [
    62,    62,    62,    62,   103,   124,    62,    41,    38,   132,
   277,    72,    72,    41,   267,   100,    72,   210,    53,   211,
    41,    67,    67,    67,    67,    38,   222,    26,   236,   315,
   103,    36,   223,   154,   153,    82,    72,   310,   161,    81,
    82,    72,   124,   220,   310,    60,    60,   373,   310,    42,
    60,   219,    43,    44,   133,    45,    31,    32,   302,   218,
    34,    35,    46,    47,   104,    60,   275,    30,   229,    29,
    28,    25,    63,   229,    37,    27,    24,    62,    41,    38,
    37,    69,    69,    69,    69,    33,    61,    37,    99,    53,
   104,    37,    81,    82,   115,   357,    61,   116,    26,   319,
   338,   337,    36,   161,    81,    82,    72,   161,    81,    82,
    72,   305,   306,    98,    81,    82,    72,    72,    82,    72,
    42,   319,   231,    43,    44,   319,    45,    31,    32,    82,
    72,    34,    35,    46,    47,    98,    60,   232,    30,    98,
    29,    28,    25,    63,   323,    37,    27,    24,    62,    41,
    38,    60,   325,   225,   205,   226,    33,    61,   118,   233,
    53,    61,   257,   107,   211,    61,   323,   119,   120,    26,
   323,   236,   217,    36,   325,   354,   205,   216,   325,   237,
   205,   351,   352,   353,   355,   369,    81,    82,    72,   215,
   214,    42,   213,   240,    43,    44,   124,    45,    31,    32,
   124,   243,    34,    35,    46,    47,   244,    60,   212,    30,
   206,    29,    28,    25,    63,   246,    37,    27,    24,    62,
    41,    38,    81,    82,    72,   247,   248,    33,    61,   249,
   250,    53,   251,   252,   184,   183,   181,   182,   179,   175,
    26,   178,   176,   253,    36,    81,    82,    72,    81,    82,
    72,    81,    82,    72,    81,    82,    81,    82,    72,   254,
   255,   256,    42,   205,   203,    43,    44,    98,    45,    31,
    32,   202,   259,    34,    35,    46,    47,   190,    60,   261,
    30,   201,    29,    28,    25,    63,   124,    37,    27,    24,
   124,   180,   271,   177,   190,   193,   188,   273,    33,    61,
    81,    82,    72,   187,    95,    81,    82,    72,   278,    95,
   124,    88,   283,    98,   284,   285,    88,   286,    98,    81,
    82,    72,   287,    95,    81,    82,    72,   288,    95,   289,
    88,   290,    98,   291,   292,    88,    60,    98,    81,    82,
    72,    60,    95,    81,    82,    72,    82,    95,    96,    88,
   294,    98,   295,    96,    88,    60,    98,    61,   296,   124,
    60,   124,    61,    72,   300,   124,   303,    96,   304,    81,
    82,    72,    96,    95,    60,   103,    61,   307,   308,    60,
    88,    61,    98,    81,    82,    72,    96,    95,    81,    82,
    72,    96,    95,   129,    88,    61,    98,   127,   124,    88,
    61,    98,    81,    82,    72,    60,    95,    81,    82,    72,
   221,    95,   316,    88,   124,    98,   123,    96,    88,    60,
    98,    81,    82,    72,    60,    95,    61,   124,   327,   328,
   329,    96,    88,   330,    98,    99,    96,    72,    60,   117,
    61,   335,   277,    60,    72,    61,   124,    81,    82,    72,
    96,    95,    33,   113,   190,    96,   335,    60,   124,    61,
    98,    72,   348,   349,    61,   350,    33,   105,   358,    96,
   359,   360,   361,   362,   363,   364,   124,   366,    61,    76,
    75,    72,    74,    60,    33,    70,   380,   381,   382,   137,
   138,   141,   142,   139,   140,    96,   143,   144,   146,   147,
   148,   150,   145,   149,   137,   138,   141,   142,   139,   140,
   383,   143,   144,   146,   147,   148,   150,   145,   149,   384,
   190,   385,   387,   388,    64,   392,    72,   137,   138,   141,
   142,   139,   140,   207,   143,   144,   146,   147,   148,   150,
   145,   149,   190,   394,   nil,   nil,   nil,   nil,   209,   137,
   138,   141,   142,   139,   140,   nil,   143,   144,   146,   147,
   148,   150,   145,   149,   190,   nil,   nil,   nil,   nil,   nil,
   nil,   137,   138,   141,   142,   139,   140,   nil,   143,   144,
   146,   147,   148,   150,   145,   149,   137,   138,   141,   142,
   139,   140,   nil,   143,   144,   146,   147,   148,   150,   145,
   149,   137,   138,   141,   142,   139,   140,   nil,   143,   144,
   146,   147,   148,   150,   145,   149,   137,   138,   141,   142,
   139,   140,   nil,   143,   144,   146,   147,   148,   150,   145,
   149,   137,   138,   141,   142,   139,   140,   nil,   143,   144,
   146,   147,   148,   150,   145,   149,   137,   138,   141,   142,
   139,   140,   nil,   143,   144,   146,   147,   148,   150,   145,
   149,   137,   138,   141,   142,   139,   140,   nil,   143,   144,
   146,   147,   148,   150,   145,   149,   137,   138,   141,   142,
   139,   140,   nil,   143,   144,   146,   147,   148,   150,   145,
   149 ]

racc_action_check = [
   314,    65,   311,     3,    72,   274,     2,     2,     2,    70,
   242,    29,    28,   297,   234,    36,   107,   155,     2,   155,
   298,   314,    65,   311,     3,   385,   186,     2,   234,   299,
    36,     2,   186,    97,    97,   360,   360,   297,   188,   188,
   188,   188,   345,   183,   298,    29,    28,   360,   385,     2,
   107,   182,     2,     2,    70,     2,     2,     2,   274,   181,
     2,     2,     2,     2,    72,     2,   242,     2,   191,     2,
     2,     2,     2,   192,     2,     2,     2,   227,   227,   227,
   297,   314,    65,   311,     3,     2,     2,   298,    36,   227,
    36,   385,   226,   226,    48,   345,   188,    48,   227,   303,
   322,   322,   227,    99,    99,    99,    99,   211,   211,   211,
   211,   282,   282,   303,   362,   362,   362,    38,   295,   295,
   227,   365,   193,   227,   227,   339,   227,   227,   227,   231,
   231,   227,   227,   227,   227,   365,   227,   194,   227,   339,
   227,   227,   227,   227,   303,   227,   227,   227,     0,     0,
     0,    38,   303,   189,   303,   189,   227,   227,    55,   195,
     0,    99,   224,    38,   224,   211,   365,    55,    55,     0,
   339,   196,   180,     0,   365,   344,   365,   179,   339,   199,
   339,   344,   344,   344,   344,   359,   359,   359,   359,   178,
   177,     0,   176,   203,     0,     0,   204,     0,     0,     0,
   205,   206,     0,     0,     0,     0,   207,     0,   175,     0,
   134,     0,     0,     0,     0,   212,     0,     0,     0,   190,
   190,   190,    34,    34,    34,   213,   214,     0,     0,   215,
   216,   190,   217,   218,   100,   100,   100,   100,   100,   100,
   190,   100,   100,   219,   190,   236,   236,   236,   240,   240,
   240,   328,   328,   328,   100,   100,    75,    75,    75,   220,
   221,   222,   190,   125,   123,   190,   190,   100,   190,   190,
   190,   120,   228,   190,   190,   190,   190,   229,   190,   230,
   190,   119,   190,   190,   190,   190,   117,   190,   190,   190,
   114,   100,   237,   100,   113,   111,   105,   241,   190,   190,
    45,    45,    45,   104,    45,    42,    42,    42,   243,    42,
   244,    45,   246,    45,   247,   248,    42,   249,    42,    43,
    43,    43,   250,    43,   115,   115,   115,   251,   115,   252,
    43,   253,    43,   254,   255,   115,    45,   115,    96,    96,
    96,    42,    96,    76,    76,    76,   256,    76,    45,    96,
   258,    96,   262,    42,    76,    43,    76,    45,   265,   267,
   115,   268,    42,   271,   272,   103,   277,    43,   279,   201,
   201,   201,   115,   201,    96,   101,    43,   293,   294,    76,
   201,   115,   201,   202,   202,   202,    96,   202,   136,   136,
   136,    76,   136,    68,   202,    96,   202,    64,    63,   136,
    76,   136,    35,    35,    35,   201,    35,   116,   116,   116,
   184,   116,   301,    35,   302,    35,    60,   201,   116,   202,
   116,   118,   118,   118,   136,   118,   201,   304,   305,   306,
   308,   202,   118,   309,   118,   310,   136,    58,    35,    53,
   202,   315,   317,   116,    47,   136,   325,    88,    88,    88,
    35,    88,   327,    46,   330,   116,   333,   118,   335,    35,
    88,    44,   340,   341,   116,   342,    41,    37,   349,   118,
   351,   352,   353,   354,   355,   356,   357,   358,   118,    32,
    31,   361,    30,    88,   363,    27,   367,   368,   370,   135,
   135,   135,   135,   135,   135,    88,   135,   135,   135,   135,
   135,   135,   135,   135,   152,   152,   152,   152,   152,   152,
   373,   152,   152,   152,   152,   152,   152,   152,   152,   374,
   112,   375,   378,   381,     1,   386,   387,   112,   112,   112,
   112,   112,   112,   135,   112,   112,   112,   112,   112,   112,
   112,   112,   110,   389,   nil,   nil,   nil,   nil,   152,   110,
   110,   110,   110,   110,   110,   nil,   110,   110,   110,   110,
   110,   110,   110,   110,   109,   nil,   nil,   nil,   nil,   nil,
   nil,   109,   109,   109,   109,   109,   109,   nil,   109,   109,
   109,   109,   109,   109,   109,   109,   208,   208,   208,   208,
   208,   208,   nil,   208,   208,   208,   208,   208,   208,   208,
   208,   197,   197,   197,   197,   197,   197,   nil,   197,   197,
   197,   197,   197,   197,   197,   197,   239,   239,   239,   239,
   239,   239,   nil,   239,   239,   239,   239,   239,   239,   239,
   239,   200,   200,   200,   200,   200,   200,   nil,   200,   200,
   200,   200,   200,   200,   200,   200,   238,   238,   238,   238,
   238,   238,   nil,   238,   238,   238,   238,   238,   238,   238,
   238,   198,   198,   198,   198,   198,   198,   nil,   198,   198,
   198,   198,   198,   198,   198,   198,    83,    83,    83,    83,
    83,    83,   nil,    83,    83,    83,    83,    83,    83,    83,
    83 ]

racc_action_pointer = [
   144,   524,     2,    -1,   nil,   nil,   nil,   nil,   nil,   nil,
   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,
   nil,   nil,   nil,   nil,   nil,   nil,   nil,   455,   -17,   -18,
   456,   405,   404,   nil,   195,   375,    13,   438,    88,   nil,
   nil,   383,   278,   292,   432,   273,   424,   415,    47,   nil,
   nil,   nil,   nil,   422,   nil,   128,   nil,   nil,   408,   nil,
   341,   nil,   nil,   373,   397,    -3,   nil,   nil,   368,   nil,
   -17,   nil,   -13,   nil,   nil,   229,   316,   nil,   nil,   nil,
   nil,   nil,   nil,   644,   nil,   nil,   nil,   nil,   420,   nil,
   nil,   nil,   nil,   nil,   nil,   nil,   311,     6,   nil,    77,
   227,   358,   nil,   340,   226,   221,   nil,   -13,   nil,   539,
   517,   243,   495,   269,   265,   297,   380,   261,   394,   251,
   241,   nil,   nil,   238,   nil,   182,   nil,   nil,   nil,   nil,
   nil,   nil,   nil,   nil,   132,   457,   361,   nil,   nil,   nil,
   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,
   nil,   nil,   472,   nil,   nil,   -59,   nil,   nil,   nil,   nil,
   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,
   nil,   nil,   nil,   nil,   nil,   129,   113,   111,   110,    98,
    93,   -20,   -28,   -36,   331,   nil,     3,   nil,    12,    77,
   215,    20,    25,    47,    88,   110,   109,   569,   629,   161,
   599,   342,   356,   115,   171,   175,   175,   189,   554,   nil,
   nil,    81,   187,   197,   198,   201,   202,   204,   205,   215,
   231,   232,   186,   nil,    86,   nil,    65,    73,   223,   252,
   230,   101,   nil,   nil,   -34,   nil,   218,   217,   614,   584,
   221,   248,   -16,   232,   285,   nil,   232,   234,   235,   237,
   242,   247,   249,   251,   253,   254,   318,   nil,   272,   nil,
   nil,   nil,   334,   nil,   nil,   309,   nil,   334,   336,   nil,
   nil,   334,   288,   nil,   -20,   nil,   nil,   289,   nil,   351,
   nil,   nil,    55,   nil,   nil,   nil,   nil,   nil,   nil,   nil,
   nil,   nil,   nil,   301,   352,    90,   nil,     8,    15,   -47,
   nil,   330,   389,    73,   402,   353,   354,   nil,   354,   357,
   360,    -2,   nil,   nil,    -4,   424,   nil,   416,   nil,   nil,
   nil,   nil,    73,   nil,   nil,   421,   nil,   369,   224,   nil,
   429,   nil,   nil,   439,   nil,   433,   nil,   nil,   nil,    99,
   386,   385,   416,   nil,   162,    17,   nil,   nil,   nil,   442,
   nil,   395,   396,   397,   398,   399,   395,   451,   401,   159,
     7,   452,    87,   401,   nil,    95,   nil,   410,   409,   nil,
   412,   nil,   nil,   482,   443,   443,   nil,   nil,   444,   nil,
   nil,   497,   nil,   nil,   nil,    19,   449,   497,   nil,   467,
   nil,   nil,   nil,   nil,   nil ]

racc_action_default = [
    -2,  -213,    -1,  -191,    -8,    -9,   -10,   -11,   -12,   -13,
   -14,   -15,   -16,   -17,   -18,   -19,   -20,   -21,   -22,   -23,
   -24,   -25,   -26,   -27,   -28,   -29,   -30,  -213,  -213,  -213,
  -213,  -213,  -213,   -45,  -213,  -213,  -118,  -213,  -213,   -61,
   -62,  -213,  -213,  -213,  -213,  -213,  -213,  -213,   -81,   -84,
   -85,   -86,   -87,  -213,  -111,  -213,  -116,  -117,  -213,  -126,
  -213,  -186,  -187,  -193,  -213,  -191,    -3,  -188,    -7,  -190,
  -213,   -34,  -118,   -35,   -36,  -213,  -213,   -46,  -103,  -104,
  -161,  -162,  -163,   -47,  -129,  -130,  -131,  -132,  -213,  -149,
  -150,  -151,  -152,  -153,  -154,  -155,  -213,  -213,  -160,   -52,
  -213,  -119,  -121,  -193,  -213,  -213,   -58,  -213,   -63,  -213,
  -213,  -213,  -213,  -213,  -193,  -213,  -213,  -193,  -213,  -213,
  -213,  -120,  -127,  -213,  -192,  -213,  -195,   395,    -4,    -6,
  -189,   -31,   -32,   -33,  -213,  -213,  -213,  -135,  -136,  -137,
  -138,  -139,  -140,  -141,  -142,  -143,  -144,  -145,  -146,  -147,
  -148,  -133,  -213,  -158,  -159,  -213,   -50,   -53,   -54,   -55,
   -56,   -57,  -112,  -164,  -165,  -166,  -167,  -168,  -169,  -170,
  -171,  -172,  -173,  -174,  -175,  -213,  -213,  -213,  -213,  -213,
  -213,  -213,  -213,  -213,  -213,  -122,  -213,  -128,   -52,  -213,
  -213,   -89,   -89,  -213,  -213,  -213,  -213,   -82,   -83,  -213,
  -113,  -213,  -213,  -213,  -193,  -193,  -213,   -38,  -134,  -156,
   -48,  -213,  -213,  -213,  -213,  -213,  -213,  -213,  -213,  -213,
  -213,  -213,  -123,  -125,  -213,   -59,  -213,    -5,  -213,  -213,
  -213,  -213,   -67,   -70,   -78,   -72,  -213,  -213,  -114,  -115,
  -213,  -213,  -213,  -213,  -193,   -51,  -213,  -213,  -213,  -213,
  -213,  -213,  -213,  -213,  -213,  -213,  -213,   -49,  -213,   -64,
   -88,   -65,  -213,   -68,   -69,  -213,   -73,  -193,  -193,   -75,
   -76,  -213,  -213,  -194,  -193,  -197,  -198,  -213,   -37,   -39,
   -41,   -42,  -213,  -176,  -177,  -178,  -179,  -180,  -181,  -182,
  -183,  -184,  -185,  -213,  -213,  -213,   -71,  -213,  -213,  -213,
  -157,  -213,  -193,  -208,  -193,  -213,  -213,  -124,  -213,  -213,
  -213,  -191,   -79,   -80,  -191,  -213,  -196,  -213,  -200,  -201,
  -202,  -203,  -213,  -206,  -207,  -193,   -40,  -213,  -213,   -60,
  -213,   -77,   -74,   -90,   -91,  -193,  -199,  -204,  -205,  -208,
  -213,  -213,  -213,   -92,  -213,  -193,  -210,  -212,   -43,  -213,
   -66,  -213,  -213,  -213,  -213,  -213,  -213,  -193,  -213,  -213,
  -213,  -213,  -213,  -213,  -209,  -208,   -44,  -213,  -213,  -110,
  -213,   -98,   -99,  -213,  -213,  -213,  -107,  -108,  -102,  -211,
   -93,  -213,   -94,  -100,   -95,  -213,  -213,  -213,  -109,  -213,
  -105,  -106,   -97,  -101,   -96 ]

racc_goto_table = [
    39,   108,    39,    68,    78,    66,   125,     9,    77,     9,
    65,   186,    40,     2,    40,   155,   191,   192,   276,   194,
   195,   263,   196,   312,   312,   199,    71,    73,    39,    39,
   262,   279,   346,   334,    79,   324,   106,   164,    39,   235,
    40,    40,   313,   313,   111,    78,   293,   114,   268,   134,
    40,   343,   311,   314,    83,   228,   230,   234,   379,   333,
   391,   109,   110,   367,   112,    68,   370,   128,   375,   157,
   169,   324,   389,   386,   162,    79,   121,   266,   185,   122,
   151,   170,   245,   163,   265,   263,   165,   166,   167,   168,
   171,   326,   172,   336,   309,   135,   173,   324,   174,   158,
   131,   204,   274,   130,   224,   189,   160,    39,   318,   345,
     1,   390,   nil,   nil,   nil,   152,   nil,   nil,   nil,    40,
   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,
   nil,   nil,   nil,   nil,   197,   198,   260,   200,   nil,   nil,
   nil,   nil,   nil,   nil,   nil,   nil,   nil,   241,   242,   nil,
   371,   nil,   282,   nil,   nil,   208,   nil,   nil,   157,   nil,
   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,
   nil,   nil,   nil,   nil,   nil,   297,   298,   nil,   nil,   nil,
   nil,   157,   nil,   nil,   nil,   nil,   nil,   nil,   158,   nil,
    39,   nil,   nil,   nil,   nil,   160,   258,     9,   nil,   nil,
   nil,   nil,    40,   227,   nil,   nil,   269,   nil,   nil,   nil,
    78,   158,   282,   nil,   272,   nil,   nil,   301,   160,   nil,
   238,   239,   nil,   nil,   nil,   nil,   nil,    39,   nil,   nil,
   nil,   264,   nil,   nil,     9,    65,   270,   342,   nil,    40,
    79,   nil,   nil,   344,   nil,   317,   nil,   nil,   nil,   nil,
   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,
   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   339,   nil,
   nil,   299,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,
   nil,   nil,   nil,   nil,   nil,   nil,   nil,   340,   356,   nil,
   nil,   nil,   nil,   nil,   nil,   264,   nil,   nil,    78,   nil,
   365,   nil,   341,   nil,   nil,   nil,   nil,   nil,   nil,   nil,
   nil,    68,   nil,   331,    68,   nil,   332,   nil,   nil,   nil,
   nil,   nil,   nil,   378,   nil,   nil,   nil,   nil,    79,    78,
   nil,   nil,   377,   368,   nil,   nil,   nil,   nil,   nil,   nil,
   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,
   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,    79,
   372,   374,   376,   nil,   nil,   nil,   nil,   nil,   nil,   nil,
   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,
   nil,   nil,   nil,   nil,   nil,   nil,   nil,   393 ]

racc_goto_check = [
    40,    35,    40,     7,    39,     4,    87,    12,    29,    12,
     3,    34,    43,     2,    43,    37,     5,     5,    90,     5,
     5,    47,    34,    36,    36,    34,    28,    28,    40,    40,
    46,    31,    95,    56,    40,    76,    28,    78,    40,    50,
    43,    43,    44,    44,    40,    39,    47,    40,    51,    29,
    43,    56,    52,    52,    30,    45,    45,    48,    95,    55,
    42,    30,    30,    57,    30,     7,    58,     4,    59,    39,
    39,    76,    60,    61,    62,    40,    63,    50,    67,    68,
    71,    73,    38,    77,    49,    47,    79,    80,    81,    82,
    83,    31,    84,    90,    46,    30,    85,    76,    86,    40,
    27,    88,    89,     6,    37,    28,    12,    40,    91,    94,
     1,    36,   nil,   nil,   nil,    30,   nil,   nil,   nil,    43,
   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,
   nil,   nil,   nil,   nil,    30,    30,     5,    30,   nil,   nil,
   nil,   nil,   nil,   nil,   nil,   nil,   nil,    87,    87,   nil,
    47,   nil,    34,   nil,   nil,    30,   nil,   nil,    39,   nil,
   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,
   nil,   nil,   nil,   nil,   nil,    34,    34,   nil,   nil,   nil,
   nil,    39,   nil,   nil,   nil,   nil,   nil,   nil,    40,   nil,
    40,   nil,   nil,   nil,   nil,    12,    39,    12,   nil,   nil,
   nil,   nil,    43,     2,   nil,   nil,    39,   nil,   nil,   nil,
    39,    40,    34,   nil,    29,   nil,   nil,    87,    12,   nil,
    30,    30,   nil,   nil,   nil,   nil,   nil,    40,   nil,   nil,
   nil,    40,   nil,   nil,    12,     3,    40,     5,   nil,    43,
    40,   nil,   nil,    34,   nil,    87,   nil,   nil,   nil,   nil,
   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,
   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,    87,   nil,
   nil,    40,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,
   nil,   nil,   nil,   nil,   nil,   nil,   nil,    35,    87,   nil,
   nil,   nil,   nil,   nil,   nil,    40,   nil,   nil,    39,   nil,
    87,   nil,    29,   nil,   nil,   nil,   nil,   nil,   nil,   nil,
   nil,     7,   nil,     4,     7,   nil,     4,   nil,   nil,   nil,
   nil,   nil,   nil,    35,   nil,   nil,   nil,   nil,    40,    39,
   nil,   nil,    39,    29,   nil,   nil,   nil,   nil,   nil,   nil,
   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,
   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,    40,
    40,    40,    40,   nil,   nil,   nil,   nil,   nil,   nil,   nil,
   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,
   nil,   nil,   nil,   nil,   nil,   nil,   nil,    40 ]

racc_goto_pointer = [
   nil,   110,    13,     8,     2,   -93,    35,     0,   nil,   nil,
   nil,   nil,     7,   nil,   nil,   nil,   nil,   nil,   nil,   nil,
   nil,   nil,   nil,   nil,   nil,   nil,   nil,    30,    -2,   -26,
    19,  -213,   nil,   nil,   -92,   -40,  -274,   -84,  -129,   -30,
     0,   nil,  -325,    12,  -255,  -136,  -201,  -210,  -139,  -150,
  -157,  -188,  -245,   nil,   nil,  -256,  -282,  -296,  -294,  -294,
  -313,  -305,   -26,    18,   nil,   nil,   nil,   -23,    21,   nil,
   nil,    -8,   nil,   -19,   nil,   nil,  -268,   -17,   -63,   -14,
   -13,   -12,   -11,   -10,    -8,    -4,    -2,   -57,   -24,  -140,
  -224,  -195,   nil,   nil,  -230,  -307 ]

racc_goto_default = [
   nil,   nil,   nil,     3,   nil,   nil,   nil,     4,     5,     6,
     7,     8,    87,    10,    11,    12,    13,    14,    15,    16,
    17,    18,    19,    20,    21,    22,    23,   nil,    55,   nil,
   nil,   nil,   280,   281,   126,    54,    52,   nil,   156,    89,
    91,   159,    51,    92,    49,   nil,   nil,    80,   nil,   nil,
   nil,   nil,   nil,    48,    50,   nil,   nil,   nil,   nil,   nil,
   nil,   nil,   nil,    56,    57,   101,    58,   102,    59,    84,
    85,    86,   136,    90,    93,    94,    97,   nil,   nil,   nil,
   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   320,   nil,
   nil,   347,   321,   322,   nil,   nil ]

racc_reduce_table = [
  0, 0, :racc_error,
  1, 87, :_reduce_1,
  0, 87, :_reduce_none,
  2, 88, :_reduce_3,
  3, 88, :_reduce_4,
  2, 91, :_reduce_5,
  1, 92, :_reduce_none,
  0, 92, :_reduce_none,
  1, 89, :_reduce_none,
  1, 89, :_reduce_none,
  1, 89, :_reduce_none,
  1, 89, :_reduce_none,
  1, 89, :_reduce_none,
  1, 89, :_reduce_none,
  1, 89, :_reduce_none,
  1, 89, :_reduce_none,
  1, 89, :_reduce_none,
  1, 89, :_reduce_none,
  1, 89, :_reduce_none,
  1, 89, :_reduce_none,
  1, 89, :_reduce_none,
  1, 89, :_reduce_none,
  1, 89, :_reduce_none,
  1, 89, :_reduce_none,
  1, 89, :_reduce_none,
  1, 89, :_reduce_none,
  1, 89, :_reduce_none,
  1, 89, :_reduce_none,
  1, 89, :_reduce_28,
  1, 89, :_reduce_29,
  1, 112, :_reduce_30,
  3, 111, :_reduce_31,
  1, 113, :_reduce_none,
  1, 113, :_reduce_none,
  2, 110, :_reduce_34,
  2, 108, :_reduce_35,
  2, 107, :_reduce_36,
  6, 105, :_reduce_37,
  4, 105, :_reduce_38,
  6, 105, :_reduce_39,
  8, 105, :_reduce_40,
  1, 117, :_reduce_none,
  1, 117, :_reduce_none,
  5, 118, :_reduce_43,
  7, 119, :_reduce_44,
  1, 121, :_reduce_45,
  2, 103, :_reduce_46,
  2, 104, :_reduce_47,
  4, 122, :_reduce_48,
  5, 122, :_reduce_49,
  1, 123, :_reduce_50,
  3, 123, :_reduce_51,
  0, 123, :_reduce_52,
  1, 124, :_reduce_none,
  1, 124, :_reduce_none,
  1, 124, :_reduce_none,
  1, 124, :_reduce_none,
  1, 127, :_reduce_57,
  2, 128, :_reduce_58,
  4, 128, :_reduce_59,
  8, 128, :_reduce_60,
  1, 114, :_reduce_none,
  1, 114, :_reduce_none,
  2, 130, :_reduce_63,
  5, 99, :_reduce_64,
  5, 99, :_reduce_65,
  10, 101, :_reduce_66,
  4, 102, :_reduce_67,
  1, 132, :_reduce_none,
  1, 132, :_reduce_none,
  4, 95, :_reduce_70,
  6, 106, :_reduce_71,
  1, 134, :_reduce_72,
  2, 134, :_reduce_73,
  5, 136, :_reduce_74,
  1, 137, :_reduce_none,
  1, 137, :_reduce_none,
  4, 135, :_reduce_77,
  0, 135, :_reduce_none,
  1, 138, :_reduce_none,
  1, 138, :_reduce_none,
  1, 100, :_reduce_none,
  3, 100, :_reduce_82,
  3, 100, :_reduce_83,
  1, 139, :_reduce_none,
  1, 139, :_reduce_none,
  1, 139, :_reduce_none,
  1, 139, :_reduce_none,
  2, 131, :_reduce_88,
  0, 131, :_reduce_89,
  8, 96, :_reduce_90,
  1, 141, :_reduce_91,
  2, 141, :_reduce_92,
  6, 142, :_reduce_93,
  6, 142, :_reduce_94,
  6, 142, :_reduce_95,
  8, 142, :_reduce_96,
  7, 142, :_reduce_97,
  1, 144, :_reduce_none,
  1, 144, :_reduce_none,
  2, 144, :_reduce_100,
  2, 147, :_reduce_101,
  0, 147, :_reduce_none,
  1, 115, :_reduce_none,
  1, 115, :_reduce_none,
  1, 146, :_reduce_none,
  1, 146, :_reduce_none,
  1, 145, :_reduce_none,
  1, 145, :_reduce_none,
  3, 143, :_reduce_109,
  1, 143, :_reduce_110,
  1, 97, :_reduce_111,
  3, 94, :_reduce_112,
  3, 140, :_reduce_113,
  4, 140, :_reduce_114,
  4, 140, :_reduce_115,
  1, 126, :_reduce_none,
  1, 126, :_reduce_none,
  1, 149, :_reduce_118,
  2, 149, :_reduce_119,
  2, 150, :_reduce_120,
  1, 151, :_reduce_121,
  2, 151, :_reduce_122,
  3, 153, :_reduce_123,
  6, 153, :_reduce_124,
  3, 153, :_reduce_125,
  1, 152, :_reduce_126,
  2, 152, :_reduce_127,
  3, 154, :_reduce_128,
  1, 116, :_reduce_none,
  1, 116, :_reduce_none,
  1, 155, :_reduce_131,
  1, 155, :_reduce_none,
  2, 155, :_reduce_133,
  3, 156, :_reduce_134,
  1, 158, :_reduce_135,
  1, 158, :_reduce_136,
  1, 158, :_reduce_137,
  1, 158, :_reduce_138,
  1, 158, :_reduce_139,
  1, 158, :_reduce_140,
  1, 158, :_reduce_141,
  1, 158, :_reduce_142,
  1, 158, :_reduce_143,
  1, 158, :_reduce_144,
  1, 158, :_reduce_145,
  1, 158, :_reduce_146,
  1, 158, :_reduce_147,
  1, 158, :_reduce_148,
  1, 157, :_reduce_none,
  1, 157, :_reduce_none,
  1, 157, :_reduce_none,
  1, 157, :_reduce_none,
  1, 157, :_reduce_none,
  1, 157, :_reduce_none,
  1, 161, :_reduce_155,
  3, 160, :_reduce_156,
  6, 129, :_reduce_157,
  2, 159, :_reduce_158,
  2, 159, :_reduce_159,
  1, 162, :_reduce_160,
  1, 125, :_reduce_none,
  1, 125, :_reduce_162,
  1, 133, :_reduce_163,
  1, 148, :_reduce_none,
  1, 148, :_reduce_none,
  1, 148, :_reduce_none,
  1, 148, :_reduce_none,
  1, 148, :_reduce_none,
  1, 148, :_reduce_none,
  1, 148, :_reduce_none,
  1, 148, :_reduce_none,
  1, 148, :_reduce_none,
  1, 148, :_reduce_none,
  1, 148, :_reduce_none,
  1, 148, :_reduce_none,
  4, 172, :_reduce_176,
  4, 171, :_reduce_177,
  4, 170, :_reduce_178,
  4, 169, :_reduce_179,
  4, 168, :_reduce_180,
  4, 167, :_reduce_181,
  4, 163, :_reduce_182,
  4, 166, :_reduce_183,
  4, 164, :_reduce_184,
  4, 165, :_reduce_185,
  1, 98, :_reduce_186,
  1, 93, :_reduce_187,
  1, 90, :_reduce_188,
  2, 90, :_reduce_189,
  1, 90, :_reduce_none,
  0, 90, :_reduce_none,
  1, 120, :_reduce_192,
  0, 120, :_reduce_none,
  5, 109, :_reduce_194,
  1, 173, :_reduce_none,
  5, 174, :_reduce_196,
  3, 174, :_reduce_197,
  1, 175, :_reduce_198,
  4, 175, :_reduce_199,
  3, 176, :_reduce_200,
  1, 177, :_reduce_none,
  1, 177, :_reduce_none,
  1, 177, :_reduce_none,
  2, 177, :_reduce_204,
  2, 177, :_reduce_205,
  1, 177, :_reduce_206,
  1, 179, :_reduce_none,
  0, 179, :_reduce_none,
  5, 178, :_reduce_209,
  1, 180, :_reduce_210,
  4, 180, :_reduce_211,
  1, 181, :_reduce_none ]

racc_reduce_n = 213

racc_shift_n = 395

racc_token_table = {
  false => 0,
  :error => 1,
  :ASSIGN => 2,
  :AT_SYM => 3,
  :COMMENT => 4,
  :JUMP => 5,
  :IO_METHOD => 6,
  :INPUT => 7,
  :OUTPUT => 8,
  :NUMREG => 9,
  :POSREG => 10,
  :VREG => 11,
  :SREG => 12,
  :TIME_SEGMENT => 13,
  :ARG => 14,
  :UALM => 15,
  :MOVE => 16,
  :DOT => 17,
  :TO => 18,
  :AT => 19,
  :TERM => 20,
  :OFFSET => 21,
  :SKIP => 22,
  :GROUP => 23,
  :SEMICOLON => 24,
  :NEWLINE => 25,
  :STRING => 26,
  :REAL => 27,
  :DIGIT => 28,
  :WORD => 29,
  :EQUAL => 30,
  :LPOS => 31,
  :EEQUAL => 32,
  :NOTEQUAL => 33,
  :GTE => 34,
  :LTE => 35,
  :LT => 36,
  :GT => 37,
  :BANG => 38,
  :PLUS => 39,
  :MINUS => 40,
  :STAR => 41,
  :SLASH => 42,
  :DIV => 43,
  :AND => 44,
  :OR => 45,
  :MOD => 46,
  :IF => 47,
  :ELSE => 48,
  :END => 49,
  :UNLESS => 50,
  :FOR => 51,
  :IN => 52,
  :WHILE => 53,
  :WAIT_FOR => 54,
  :WAIT_UNTIL => 55,
  :TIMEOUT => 56,
  :AFTER => 57,
  :FANUC_USE => 58,
  :SET_SKIP_CONDITION => 59,
  :NAMESPACE => 60,
  :CASE => 61,
  :WHEN => 62,
  :INDIRECT => 63,
  :POSITION => 64,
  :EVAL => 65,
  :TIMER => 66,
  :TIMER_METHOD => 67,
  :RAISE => 68,
  :ABORT => 69,
  :POSITION_DATA => 70,
  :TRUE_FALSE => 71,
  :RUN => 72,
  :TP_HEADER => 73,
  :PAUSE => 74,
  :LPAREN => 75,
  :RPAREN => 76,
  :COLON => 77,
  :COMMA => 78,
  :LBRACK => 79,
  :RBRACK => 80,
  :LBRACE => 81,
  :RBRACE => 82,
  :LABEL => 83,
  :ADDRESS => 84,
  :false => 85 }

racc_nt_base = 86

racc_use_result_var = true

Racc_arg = [
  racc_action_table,
  racc_action_check,
  racc_action_default,
  racc_action_pointer,
  racc_goto_table,
  racc_goto_check,
  racc_goto_default,
  racc_goto_pointer,
  racc_nt_base,
  racc_reduce_table,
  racc_token_table,
  racc_shift_n,
  racc_reduce_n,
  racc_use_result_var ]

Racc_token_to_s_table = [
  "$end",
  "error",
  "ASSIGN",
  "AT_SYM",
  "COMMENT",
  "JUMP",
  "IO_METHOD",
  "INPUT",
  "OUTPUT",
  "NUMREG",
  "POSREG",
  "VREG",
  "SREG",
  "TIME_SEGMENT",
  "ARG",
  "UALM",
  "MOVE",
  "DOT",
  "TO",
  "AT",
  "TERM",
  "OFFSET",
  "SKIP",
  "GROUP",
  "SEMICOLON",
  "NEWLINE",
  "STRING",
  "REAL",
  "DIGIT",
  "WORD",
  "EQUAL",
  "LPOS",
  "EEQUAL",
  "NOTEQUAL",
  "GTE",
  "LTE",
  "LT",
  "GT",
  "BANG",
  "PLUS",
  "MINUS",
  "STAR",
  "SLASH",
  "DIV",
  "AND",
  "OR",
  "MOD",
  "IF",
  "ELSE",
  "END",
  "UNLESS",
  "FOR",
  "IN",
  "WHILE",
  "WAIT_FOR",
  "WAIT_UNTIL",
  "TIMEOUT",
  "AFTER",
  "FANUC_USE",
  "SET_SKIP_CONDITION",
  "NAMESPACE",
  "CASE",
  "WHEN",
  "INDIRECT",
  "POSITION",
  "EVAL",
  "TIMER",
  "TIMER_METHOD",
  "RAISE",
  "ABORT",
  "POSITION_DATA",
  "TRUE_FALSE",
  "RUN",
  "TP_HEADER",
  "PAUSE",
  "LPAREN",
  "RPAREN",
  "COLON",
  "COMMA",
  "LBRACK",
  "RBRACK",
  "LBRACE",
  "RBRACE",
  "LABEL",
  "ADDRESS",
  "false",
  "$start",
  "program",
  "statements",
  "statement",
  "terminator",
  "block",
  "optional_newline",
  "comment",
  "definition",
  "namespace",
  "motion_statement",
  "label_definition",
  "address",
  "conditional",
  "inline_conditional",
  "forloop",
  "while_loop",
  "use_statement",
  "set_skip_statement",
  "wait_statement",
  "case_statement",
  "fanuc_eval",
  "timer_method",
  "position_data",
  "raise",
  "tp_header_definition",
  "empty_stmt",
  "tp_header_value",
  "var_or_indirect",
  "indirectable",
  "expression",
  "wait_modifier",
  "timeout_modifier",
  "after_modifier",
  "swallow_newlines",
  "label",
  "program_call",
  "args",
  "arg",
  "number",
  "var",
  "string",
  "io_method",
  "indirect_thing",
  "jump",
  "else_block",
  "minmax_val",
  "integer",
  "case_conditions",
  "case_else",
  "case_condition",
  "case_allowed_condition",
  "case_allowed_statement",
  "inlineable",
  "assignment",
  "motion_modifiers",
  "motion_modifier",
  "speed",
  "valid_terminations",
  "time",
  "time_seg_actions",
  "optional_lpos_arg",
  "definable",
  "var_without_namespaces",
  "var_with_namespaces",
  "var_method_modifiers",
  "namespaces",
  "var_method_modifier",
  "ns",
  "unary_expression",
  "binary_expression",
  "factor",
  "operator",
  "signed_number",
  "paren_expr",
  "lpos",
  "sign",
  "numreg",
  "output",
  "input",
  "posreg",
  "position",
  "vreg",
  "argument",
  "timer",
  "ualm",
  "sreg",
  "sn",
  "hash",
  "hash_attributes",
  "hash_attribute",
  "hash_value",
  "array",
  "optional_sign",
  "array_values",
  "array_value" ]

Racc_debug_parser = true

##### State transition tables end #####

# reduce 0 omitted

def _reduce_1(val, _values, result)
 @interpreter.nodes = val[0] 
    result
end

# reduce 2 omitted

def _reduce_3(val, _values, result)
                                          result = [val[0]]
                                          result << val[1] unless val[1].nil?
                                        
    result
end

def _reduce_4(val, _values, result)
                                          result = val[0] << val[1]
                                          result << val[2] unless val[2].nil?
                                        
    result
end

def _reduce_5(val, _values, result)
 result = val[1] 
    result
end

# reduce 6 omitted

# reduce 7 omitted

# reduce 8 omitted

# reduce 9 omitted

# reduce 10 omitted

# reduce 11 omitted

# reduce 12 omitted

# reduce 13 omitted

# reduce 14 omitted

# reduce 15 omitted

# reduce 16 omitted

# reduce 17 omitted

# reduce 18 omitted

# reduce 19 omitted

# reduce 20 omitted

# reduce 21 omitted

# reduce 22 omitted

# reduce 23 omitted

# reduce 24 omitted

# reduce 25 omitted

# reduce 26 omitted

# reduce 27 omitted

def _reduce_28(val, _values, result)
 result = PauseNode.new 
    result
end

def _reduce_29(val, _values, result)
 result = AbortNode.new 
    result
end

def _reduce_30(val, _values, result)
 result = EmptyStmtNode.new() 
    result
end

def _reduce_31(val, _values, result)
 result = HeaderNode.new(val[0],val[2]) 
    result
end

# reduce 32 omitted

# reduce 33 omitted

def _reduce_34(val, _values, result)
 result = RaiseNode.new(val[1]) 
    result
end

def _reduce_35(val, _values, result)
 result = TimerMethodNode.new(val[0],val[1]) 
    result
end

def _reduce_36(val, _values, result)
 result = EvalNode.new(val[1]) 
    result
end

def _reduce_37(val, _values, result)
 result = WaitForNode.new(val[2], val[4]) 
    result
end

def _reduce_38(val, _values, result)
 result = WaitUntilNode.new(val[2], nil) 
    result
end

def _reduce_39(val, _values, result)
 result = WaitUntilNode.new(val[2],val[5]) 
    result
end

def _reduce_40(val, _values, result)
 result = WaitUntilNode.new(val[2],val[5].merge(val[7])) 
    result
end

# reduce 41 omitted

# reduce 42 omitted

def _reduce_43(val, _values, result)
 result = { label: val[3] } 
    result
end

def _reduce_44(val, _values, result)
 result = { timeout: [val[3],val[5]] } 
    result
end

def _reduce_45(val, _values, result)
 result = val[0] 
    result
end

def _reduce_46(val, _values, result)
 result = UseNode.new(val[0],val[1]) 
    result
end

def _reduce_47(val, _values, result)
 result = SetSkipNode.new(val[1]) 
    result
end

def _reduce_48(val, _values, result)
 result = CallNode.new(val[0],val[2]) 
    result
end

def _reduce_49(val, _values, result)
 result = CallNode.new(val[1],val[3],async: true) 
    result
end

def _reduce_50(val, _values, result)
 result = [val[0]] 
    result
end

def _reduce_51(val, _values, result)
 result = val[0] << val[2] 
    result
end

def _reduce_52(val, _values, result)
 result = [] 
    result
end

# reduce 53 omitted

# reduce 54 omitted

# reduce 55 omitted

# reduce 56 omitted

def _reduce_57(val, _values, result)
 result = StringNode.new(val[0]) 
    result
end

def _reduce_58(val, _values, result)
 result = IOMethodNode.new(val[0],val[1]) 
    result
end

def _reduce_59(val, _values, result)
 result = IOMethodNode.new(val[0],val[2]) 
    result
end

def _reduce_60(val, _values, result)
 result = IOMethodNode.new(val[0],val[2],{ pulse_time: val[4], pulse_units: val[6] }) 
    result
end

# reduce 61 omitted

# reduce 62 omitted

def _reduce_63(val, _values, result)
 result = JumpNode.new(val[1]) 
    result
end

def _reduce_64(val, _values, result)
 result = ConditionalNode.new("if",val[1],val[2],val[3]) 
    result
end

def _reduce_65(val, _values, result)
 result = ConditionalNode.new("unless",val[1],val[2],val[3]) 
    result
end

def _reduce_66(val, _values, result)
 result = ForNode.new(val[1],val[4],val[6],val[8]) 
    result
end

def _reduce_67(val, _values, result)
 result = WhileNode.new(val[1],val[2]) 
    result
end

# reduce 68 omitted

# reduce 69 omitted

def _reduce_70(val, _values, result)
 result = NamespaceNode.new(val[1],val[2]) 
    result
end

def _reduce_71(val, _values, result)
 result = CaseNode.new(val[1],val[3],val[4]) 
    result
end

def _reduce_72(val, _values, result)
 result = val 
    result
end

def _reduce_73(val, _values, result)
 result = val[0] << val[1] << val[2] 
    result
end

def _reduce_74(val, _values, result)
 result = CaseConditionNode.new(val[1],val[3]) 
    result
end

# reduce 75 omitted

# reduce 76 omitted

def _reduce_77(val, _values, result)
 result = CaseConditionNode.new(nil,val[2]) 
    result
end

# reduce 78 omitted

# reduce 79 omitted

# reduce 80 omitted

# reduce 81 omitted

def _reduce_82(val, _values, result)
 result = InlineConditionalNode.new(val[1], val[2], val[0]) 
    result
end

def _reduce_83(val, _values, result)
 result = InlineConditionalNode.new(val[1], val[2], val[0]) 
    result
end

# reduce 84 omitted

# reduce 85 omitted

# reduce 86 omitted

# reduce 87 omitted

def _reduce_88(val, _values, result)
 result = val[1] 
    result
end

def _reduce_89(val, _values, result)
 result = [] 
    result
end

def _reduce_90(val, _values, result)
 result = MotionNode.new(val[0],val[5],val[7]) 
    result
end

def _reduce_91(val, _values, result)
 result = val 
    result
end

def _reduce_92(val, _values, result)
 result = val[0] << val[1] 
    result
end

def _reduce_93(val, _values, result)
 result = SpeedNode.new(val[4]) 
    result
end

def _reduce_94(val, _values, result)
 result = TerminationNode.new(val[4]) 
    result
end

def _reduce_95(val, _values, result)
 result = OffsetNode.new(val[2],val[4]) 
    result
end

def _reduce_96(val, _values, result)
 result = TimeNode.new(val[2],val[4],val[6]) 
    result
end

def _reduce_97(val, _values, result)
 result = SkipNode.new(val[4],val[5]) 
    result
end

# reduce 98 omitted

# reduce 99 omitted

def _reduce_100(val, _values, result)
                                         raise Racc::ParseError, sprintf("\ninvalid termination type: (%s)", val[1]) if val[1] != 1
                                         result = DigitNode.new(val[1].to_i * -1)
                                       
    result
end

def _reduce_101(val, _values, result)
 result = val[1] 
    result
end

# reduce 102 omitted

# reduce 103 omitted

# reduce 104 omitted

# reduce 105 omitted

# reduce 106 omitted

# reduce 107 omitted

# reduce 108 omitted

def _reduce_109(val, _values, result)
 result = { speed: val[0], units: val[2] } 
    result
end

def _reduce_110(val, _values, result)
 result = { speed: val[0], units: nil } 
    result
end

def _reduce_111(val, _values, result)
 result = LabelDefinitionNode.new(val[0]) 
    result
end

def _reduce_112(val, _values, result)
 result = DefinitionNode.new(val[0],val[2]) 
    result
end

def _reduce_113(val, _values, result)
 result = AssignmentNode.new(val[0],val[2]) 
    result
end

def _reduce_114(val, _values, result)
 result = AssignmentNode.new(
                                           val[0],
                                           ExpressionNode.new(val[0],"+",val[3])
                                         )
                                       
    result
end

def _reduce_115(val, _values, result)
 result = AssignmentNode.new(
                                           val[0],
                                           ExpressionNode.new(val[0],"-",val[3])
                                         )
                                       
    result
end

# reduce 116 omitted

# reduce 117 omitted

def _reduce_118(val, _values, result)
 result = VarNode.new(val[0]) 
    result
end

def _reduce_119(val, _values, result)
 result = VarMethodNode.new(val[0],val[1]) 
    result
end

def _reduce_120(val, _values, result)
 result = NamespacedVarNode.new(val[0],val[1]) 
    result
end

def _reduce_121(val, _values, result)
 result = val[0] 
    result
end

def _reduce_122(val, _values, result)
 result = val[0].merge(val[1]) 
    result
end

def _reduce_123(val, _values, result)
 result = { group: val[2] } 
    result
end

def _reduce_124(val, _values, result)
 result = { group: val[4] } 
    result
end

def _reduce_125(val, _values, result)
 result = { method: val[2] } 
    result
end

def _reduce_126(val, _values, result)
 result = [val[0]] 
    result
end

def _reduce_127(val, _values, result)
 result = val[0] << val[1] 
    result
end

def _reduce_128(val, _values, result)
 result = val[0] 
    result
end

# reduce 129 omitted

# reduce 130 omitted

def _reduce_131(val, _values, result)
 result = val[0] 
    result
end

# reduce 132 omitted

def _reduce_133(val, _values, result)
 result = ExpressionNode.new(val[1], "!", nil) 
    result
end

def _reduce_134(val, _values, result)
 result = ExpressionNode.new(val[0], val[1], val[2]) 
    result
end

def _reduce_135(val, _values, result)
 result = "==" 
    result
end

def _reduce_136(val, _values, result)
 result = "<>" 
    result
end

def _reduce_137(val, _values, result)
 result = "<" 
    result
end

def _reduce_138(val, _values, result)
 result = ">" 
    result
end

def _reduce_139(val, _values, result)
 result = ">=" 
    result
end

def _reduce_140(val, _values, result)
 result = "<=" 
    result
end

def _reduce_141(val, _values, result)
 result = "+" 
    result
end

def _reduce_142(val, _values, result)
 result = "-" 
    result
end

def _reduce_143(val, _values, result)
 result = "||" 
    result
end

def _reduce_144(val, _values, result)
 result = "*" 
    result
end

def _reduce_145(val, _values, result)
 result = "/" 
    result
end

def _reduce_146(val, _values, result)
 result = "DIV" 
    result
end

def _reduce_147(val, _values, result)
 result = "%" 
    result
end

def _reduce_148(val, _values, result)
 result = "&&" 
    result
end

# reduce 149 omitted

# reduce 150 omitted

# reduce 151 omitted

# reduce 152 omitted

# reduce 153 omitted

# reduce 154 omitted

def _reduce_155(val, _values, result)
result = LPOSNode.new(val[0])
    result
end

def _reduce_156(val, _values, result)
 result = ParenExpressionNode.new(val[1]) 
    result
end

def _reduce_157(val, _values, result)
 result = IndirectNode.new(val[2].to_sym, val[4]) 
    result
end

def _reduce_158(val, _values, result)
                                          val[1] = val[1].to_i * -1 if val[0] == "-"
                                          result = DigitNode.new(val[1])
                                      
    result
end

def _reduce_159(val, _values, result)
 val[1] = val[1].to_f * -1 if val[0] == "-"; result = RealNode.new(val[1]) 
    result
end

def _reduce_160(val, _values, result)
 result = "-" 
    result
end

# reduce 161 omitted

def _reduce_162(val, _values, result)
 result = RealNode.new(val[0]) 
    result
end

def _reduce_163(val, _values, result)
 result = DigitNode.new(val[0]) 
    result
end

# reduce 164 omitted

# reduce 165 omitted

# reduce 166 omitted

# reduce 167 omitted

# reduce 168 omitted

# reduce 169 omitted

# reduce 170 omitted

# reduce 171 omitted

# reduce 172 omitted

# reduce 173 omitted

# reduce 174 omitted

# reduce 175 omitted

def _reduce_176(val, _values, result)
 result = StringRegisterNode.new(val[2].to_i) 
    result
end

def _reduce_177(val, _values, result)
 result = UserAlarmNode.new(val[2].to_i) 
    result
end

def _reduce_178(val, _values, result)
 result = TimerNode.new(val[2].to_i) 
    result
end

def _reduce_179(val, _values, result)
 result = ArgumentNode.new(val[2].to_i) 
    result
end

def _reduce_180(val, _values, result)
 result = VisionRegisterNode.new(val[2].to_i) 
    result
end

def _reduce_181(val, _values, result)
 result = PositionNode.new(val[2].to_i) 
    result
end

def _reduce_182(val, _values, result)
 result = NumregNode.new(val[2].to_i) 
    result
end

def _reduce_183(val, _values, result)
 result = PosregNode.new(val[2].to_i) 
    result
end

def _reduce_184(val, _values, result)
 result = IONode.new(val[0], val[2].to_i) 
    result
end

def _reduce_185(val, _values, result)
 result = IONode.new(val[0], val[2].to_i) 
    result
end

def _reduce_186(val, _values, result)
 result = AddressNode.new(val[0]) 
    result
end

def _reduce_187(val, _values, result)
 result = CommentNode.new(val[0]) 
    result
end

def _reduce_188(val, _values, result)
 result = TerminatorNode.new 
    result
end

def _reduce_189(val, _values, result)
 result = val[0] 
    result
end

# reduce 190 omitted

# reduce 191 omitted

def _reduce_192(val, _values, result)
 result = TerminatorNode.new 
    result
end

# reduce 193 omitted

def _reduce_194(val, _values, result)
 result = PositionDataNode.new(val[2]) 
    result
end

# reduce 195 omitted

def _reduce_196(val, _values, result)
 result = val[2] 
    result
end

def _reduce_197(val, _values, result)
 result = {} 
    result
end

def _reduce_198(val, _values, result)
 result = val[0] 
    result
end

def _reduce_199(val, _values, result)
 result = val[0].merge(val[3]) 
    result
end

def _reduce_200(val, _values, result)
 result = { val[0].to_sym => val[2] } 
    result
end

# reduce 201 omitted

# reduce 202 omitted

# reduce 203 omitted

def _reduce_204(val, _values, result)
 val[1] = val[1].to_i * -1 if val[0] == "-"; result = val[1] 
    result
end

def _reduce_205(val, _values, result)
 val[1] = val[1].to_f * -1 if val[0] == "-"; result = val[1] 
    result
end

def _reduce_206(val, _values, result)
 result = val[0] == "true" 
    result
end

# reduce 207 omitted

# reduce 208 omitted

def _reduce_209(val, _values, result)
 result = val[2] 
    result
end

def _reduce_210(val, _values, result)
 result = val 
    result
end

def _reduce_211(val, _values, result)
 result = val[0] << val[3] 
    result
end

# reduce 212 omitted

def _reduce_none(val, _values, result)
  val[0]
end

  end   # class Parser
  end   # module TPPlus
